const dataFunction = () => {
  const data = {
    businesses: [
      {
        id: 'nyPEn4t4dJglcWxoQRp7vA',
        alias: 'bakers-pizza-new-york-4',
        name: "Baker's Pizza",
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/C-oarJ1ocldrTOZr5Z_5XA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/bakers-pizza-new-york-4?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 114,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 40.76546,
          longitude: -73.991,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '754 10th Ave',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['754 10th Ave', 'New York, NY 10019'],
        },
        phone: '+19172620722',
        display_phone: '(917) 262-0722',
        distance: 259.1430821248716,
      },
      {
        id: 'DJSLGbSqCJ1W8ma3LFlMuw',
        alias: 'patzeria-perfect-pizza-new-york',
        name: 'Patzeria Perfect Pizza',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/w62on7rHWF6ZNTVy6M6RuQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/patzeria-perfect-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 1666,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'pastashops',
            title: 'Pasta Shops',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.759494511551836,
          longitude: -73.98673451962638,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '231 W 46th St',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['231 W 46th St', 'New York, NY 10036'],
        },
        phone: '+12125757646',
        display_phone: '(212) 575-7646',
        distance: 931.0364650504453,
      },
      {
        id: '1To57srDy-cVko5QWGcogA',
        alias: 'sacco-pizza-new-york',
        name: 'Sacco Pizza',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/HsNvqNfdNHX5hpxdeWpfjA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/sacco-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 418,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7662658691406,
          longitude: -73.9872665405273,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '819 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['819 9th Ave', 'New York, NY 10019'],
        },
        phone: '+12125827765',
        display_phone: '(212) 582-7765',
        distance: 564.2306649165632,
      },
      {
        id: 'dAoDMvczet_r65mjBSQnJA',
        alias: 'corner-slice-new-york',
        name: 'Corner Slice',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/016f1hgd9KYJSgFjGIUHNQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/corner-slice-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 130,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'sandwiches',
            title: 'Sandwiches',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7623377,
          longitude: -73.9967579,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '600 11th Ave',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['600 11th Ave', 'New York, NY 10036'],
        },
        phone: '+12129569339',
        display_phone: '(212) 956-9339',
        distance: 455.26349665708227,
      },
      {
        id: 'FKzpfWUpyupl4q74Jt8fTA',
        alias: 'don-antonio-new-york-5',
        name: 'Don Antonio',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/Kwv16TeExWDWWLLbCNq7Cw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/don-antonio-new-york-5?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 1485,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'cocktailbars',
            title: 'Cocktail Bars',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.762711,
          longitude: -73.986708,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '309 W 50th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['309 W 50th St', 'New York, NY 10019'],
        },
        phone: '+16467191043',
        display_phone: '(646) 719-1043',
        distance: 702.1205431879921,
      },
      {
        id: '3R0jr-FB09YW8goSl3yAtQ',
        alias: 'new-york-sals-pizza-new-york',
        name: "New York Sal's Pizza",
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/r6j3Q8wsctft1Z98-0q8fg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/new-york-sals-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 70,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.7637252807617,
          longitude: -73.9921112060547,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '696 10th Ave',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['696 10th Ave', 'New York, NY 10019'],
        },
        phone: '+12122473628',
        display_phone: '(212) 247-3628',
        distance: 281.3498066926344,
      },
      {
        id: 'c3D2ckzacnPtdGIM8tb-_w',
        alias: 'b-side-pizza-and-wine-bar-new-york',
        name: 'B Side Pizza & Wine Bar',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/0oC3VssQ0t1gSEEf9HWlmA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/b-side-pizza-and-wine-bar-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 1178,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'wine_bars',
            title: 'Wine Bars',
          },
          {
            alias: 'cocktailbars',
            title: 'Cocktail Bars',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 40.76388,
          longitude: -73.98821,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '370 W 51st St',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['370 W 51st St', 'New York, NY 10019'],
        },
        phone: '+16466797225',
        display_phone: '(646) 679-7225',
        distance: 530.249537061658,
      },
      {
        id: 'JgtKnRMbUQKXaxC-C0BynQ',
        alias: 'il-baretto-to-go-new-york',
        name: 'Il Baretto To Go',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/UZ1awjLkUNwgfsoymQq-lg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/il-baretto-to-go-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 41,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'salad',
            title: 'Salad',
          },
          {
            alias: 'pastashops',
            title: 'Pasta Shops',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 40.76860757932551,
          longitude: -73.99233994313758,
        },
        transactions: ['delivery', 'pickup'],
        location: {
          address1: '790 11th Ave',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['790 11th Ave', 'New York, NY 10019'],
        },
        phone: '+12122450490',
        display_phone: '(212) 245-0490',
        distance: 336.64370404985544,
      },
      {
        id: '5iVLPS-DsfEEybvdBlqEPQ',
        alias: 'ny-fresh-pizza-new-york',
        name: 'NY Fresh Pizza',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/Bg4S_YrywBLErdeiGzrPCQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ny-fresh-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 44,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.765152,
          longitude: -73.988144,
        },
        transactions: ['delivery'],
        price: '$',
        location: {
          address1: '787 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['787 9th Ave', 'New York, NY 10019'],
        },
        phone: '+12125862600',
        display_phone: '(212) 586-2600',
        distance: 495.0810488253316,
      },
      {
        id: 'ouD1xM7W3TWUhGrIxlYKXA',
        alias: '1-dollar-pizza-new-york',
        name: '1 Dollar Pizza',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/vVpLTkOzXH0xnjdJqFCDUg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/1-dollar-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 71,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.7637100635894,
          longitude: -73.9885861426592,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '748 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['748 9th Ave', 'New York, NY 10019'],
        },
        phone: '+12129770400',
        display_phone: '(212) 977-0400',
        distance: 510.013919916374,
      },
      {
        id: 'WGg0Zyl2qvTou42iJIRa2w',
        alias: 'hell-s-kitchen-pizza-new-york',
        name: 'Hell’s Kitchen Pizza',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/x8hPp0CoNqFtEUKJ3TiKTQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/hell-s-kitchen-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 10,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'delis',
            title: 'Delis',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.761941,
          longitude: -73.989672,
        },
        transactions: ['delivery', 'pickup'],
        location: {
          address1: '696 9th Ave',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10001',
          country: 'US',
          state: 'NY',
          display_address: ['696 9th Ave', 'New York, NY 10001'],
        },
        phone: '+16464846193',
        display_phone: '(646) 484-6193',
        distance: 566.8282896829493,
      },
      {
        id: 'V0zC3awsklyxC0GFzmaTLg',
        alias: 'sfilatino-italian-gourmet-new-york',
        name: 'Sfilatino Italian Gourmet',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/wQGWzGT44SH3UTO1IUdhvQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/sfilatino-italian-gourmet-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 205,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'sandwiches',
            title: 'Sandwiches',
          },
          {
            alias: 'salad',
            title: 'Salad',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7675056,
          longitude: -73.9851073,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '342 W 57th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['342 W 57th St', 'New York, NY 10019'],
        },
        phone: '+16464769856',
        display_phone: '(646) 476-9856',
        distance: 785.3608873523988,
      },
      {
        id: 'QFvcjuf6N-TRI0cpFZBDWA',
        alias: 'abitinos-pizzeria-new-york-15',
        name: "Abitino's Pizzeria",
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/AjLoY471RcCHTocagueUDw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/abitinos-pizzeria-new-york-15?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 51,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 2.5,
        coordinates: {
          latitude: 40.76448,
          longitude: -73.99172,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '730 10th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['730 10th Ave', 'New York, NY 10019'],
        },
        phone: '+12122451234',
        display_phone: '(212) 245-1234',
        distance: 243.21149247325093,
      },
      {
        id: 'EEPyJJFSDNDHFbLMhbDjNg',
        alias: 'peperino-nyc-pizza-new-york',
        name: 'Peperino NYC Pizza',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/Q_b01wjynvHCgOXY4Sb5mg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/peperino-nyc-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 78,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'wine_bars',
            title: 'Wine Bars',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.77272,
          longitude: -73.99043,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '21 West End Ave',
          address2: '',
          address3: 'West 60th Street & Freedom Place',
          city: 'New York',
          zip_code: '10023',
          country: 'US',
          state: 'NY',
          display_address: [
            '21 West End Ave',
            'West 60th Street & Freedom Place',
            'New York, NY 10023',
          ],
        },
        phone: '+12122452380',
        display_phone: '(212) 245-2380',
        distance: 826.5118186659132,
      },
      {
        id: 'QR6w6bdxpRzYvF9URmyHHg',
        alias: 'claudio-pizzeria-new-york-5',
        name: 'Claudio Pizzeria',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/OqsSzCWrDYPqyzKDqlQgXQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/claudio-pizzeria-new-york-5?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 92,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7604,
          longitude: -73.99469,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '598 10th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['598 10th Ave', 'New York, NY 10036'],
        },
        phone: '+12125863145',
        display_phone: '(212) 586-3145',
        distance: 613.3944151683612,
      },
      {
        id: 'aHzzAmjZBUXJ3EHxFdRKOQ',
        alias: 'carve-new-york',
        name: 'Carve',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/t8WzyC0advRdqhkSdrKexQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/carve-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 402,
        categories: [
          {
            alias: 'sandwiches',
            title: 'Sandwiches',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'cafes',
            title: 'Cafes',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7602042287575,
          longitude: -73.9873568460327,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '760 8th Ave',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['760 8th Ave', 'New York, NY 10036'],
        },
        phone: '+12127304949',
        display_phone: '(212) 730-4949',
        distance: 837.1214434443702,
      },
      {
        id: '0h67khyxOc4hDfY2Zpme9A',
        alias: 'z-best-pizza-new-york-2',
        name: 'Z Best Pizza',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/SEWOMKZ0-uZfN0IXATGLmA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/z-best-pizza-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 2,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.76334,
          longitude: -73.99671,
        },
        transactions: ['delivery', 'pickup'],
        location: {
          address1: '623 11th Ave',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['623 11th Ave', 'New York, NY 10036'],
        },
        phone: '+12122460303',
        display_phone: '(212) 246-0303',
        distance: 362.0260759266728,
      },
      {
        id: 'h4VCnZ2aZ33mdenS_ZI7jQ',
        alias: 'mama-mia-44-sw-new-york-2',
        name: 'Mama Mia 44 SW',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/Dpd1wHWGVawq9MTOvoBwbQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/mama-mia-44-sw-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 691,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'seafood',
            title: 'Seafood',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.759761,
          longitude: -73.992065,
        },
        transactions: ['restaurant_reservation', 'delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '621 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['621 9th Ave', 'New York, NY 10036'],
        },
        phone: '+12123154582',
        display_phone: '(212) 315-4582',
        distance: 697.5660115291895,
      },
      {
        id: 'zg9Jrtx9rqTXeaqufSOxHQ',
        alias: 'masseria-dei-vini-new-york',
        name: 'Masseria dei Vini',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/y1KQC6vTkn39sCdJ91K8NQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/masseria-dei-vini-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 475,
        categories: [
          {
            alias: 'bars',
            title: 'Bars',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7684,
          longitude: -73.98558,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$$',
        location: {
          address1: '887 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['887 9th Ave', 'New York, NY 10019'],
        },
        phone: '+12123152888',
        display_phone: '(212) 315-2888',
        distance: 752.7303102956876,
      },
      {
        id: 'KL6AUMQI_Ae7_brkK0fy_w',
        alias: 'la-vela-dining-and-bar-new-york',
        name: 'La Vela Dining & Bar',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/AYhLNNgYuceqq924RG6EQg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/la-vela-dining-and-bar-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 177,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'bars',
            title: 'Bars',
          },
          {
            alias: 'diners',
            title: 'Diners',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.761082,
          longitude: -73.997872,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '558 11th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['558 11th Ave', 'New York, NY 10036'],
        },
        phone: '+12126952112',
        display_phone: '(212) 695-2112',
        distance: 623.3612107695426,
      },
      {
        id: 'ZAmwOIFgZWYQu2Z3uqff-g',
        alias: 'abruzzi-pizza-new-york',
        name: 'Abruzzi Pizza',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/j4-q9T6KWErqckb8hSh67g/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/abruzzi-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 2,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.7602801701136,
          longitude: -73.9915431100236,
        },
        transactions: ['delivery', 'pickup'],
        location: {
          address1: '642 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['642 9th Ave', 'New York, NY 10036'],
        },
        phone: '+12122450695',
        display_phone: '(212) 245-0695',
        distance: 650.3317653250995,
      },
      {
        id: 'HhXXUpn4HlSqgWudxIcitA',
        alias: 'rubbys-pizzeria-new-york',
        name: "Rubby's Pizzeria",
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/UFBSQvqXKAFSm55fBvzVAg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/rubbys-pizzeria-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 15,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.76911,
          longitude: -73.98856,
        },
        transactions: ['delivery'],
        price: '$',
        location: {
          address1: '57th St & 10th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['57th St & 10th Ave', 'New York, NY 10019'],
        },
        phone: '+12127573707',
        display_phone: '(212) 757-3707',
        distance: 582.635122535902,
      },
      {
        id: 'opCMbGK-fvGPRSBibPzu3w',
        alias: 'famous-amadeus-pizza-new-york-6',
        name: 'Famous Amadeus Pizza',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/F9F0Q2aE8H6PuL_dA9IpAQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/famous-amadeus-pizza-new-york-6?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 268,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'burgers',
            title: 'Burgers',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7626,
          longitude: -73.98566,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '840 8th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['840 8th Ave', 'New York, NY 10019'],
        },
        phone: '+12124896187',
        display_phone: '(212) 489-6187',
        distance: 793.3223242719748,
      },
      {
        id: '-wG31d9zcEsW_aE14tX4EA',
        alias: 'sfila-pizza-new-york-2',
        name: 'Sfila Pizza',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/0kWMEeh5wxv__cNTMRN_ig/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/sfila-pizza-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 11,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.76746,
          longitude: -73.98568,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '866 9th Ave',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['866 9th Ave', 'New York, NY 10019'],
        },
        phone: '+19176974436',
        display_phone: '(917) 697-4436',
        distance: 710.6349963968173,
      },
      {
        id: 'hyBM_Xk9Hzp38acTHAHlBQ',
        alias: 'dellanima-new-york-3',
        name: "dell'anima",
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/jMyra4neg2dhy4ctIRwsxg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/dellanima-new-york-3?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 651,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.76234,
          longitude: -73.99695,
        },
        transactions: ['delivery'],
        price: '$$$',
        location: {
          address1: '600 11th Ave',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['600 11th Ave', 'New York, NY 10036'],
        },
        phone: '+12123666633',
        display_phone: '(212) 366-6633',
        distance: 455.26349665708227,
      },
      {
        id: 'PJff4lIQtTaEJhY2mWsCnA',
        alias: 'casabianca-pizzeria-new-york',
        name: 'Casabianca Pizzeria',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/dBn3-0Nf34DORISC2K74Lg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/casabianca-pizzeria-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 56,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.769474029541,
          longitude: -73.9888610839844,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '503 W 57th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['503 W 57th St', 'New York, NY 10019'],
        },
        phone: '+12123978725',
        display_phone: '(212) 397-8725',
        distance: 588.2687093510773,
      },
      {
        id: 'rupPZLhd0oRSAmVDaeYaGA',
        alias: 'bocca-di-bacco-hells-kitchen-new-york',
        name: "Bocca di Bacco Hell's Kitchen",
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/RM21GbIqI9LzQbLHxZXepw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/bocca-di-bacco-hells-kitchen-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 650,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7662168,
          longitude: -73.9867943,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '828 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['828 9th Ave', 'New York, NY 10019'],
        },
        phone: '+12122658828',
        display_phone: '(212) 265-8828',
        distance: 604.2354485301239,
      },
      {
        id: 'DoSU8IPq-Py_YV3kYmXPfQ',
        alias: 'trattoria-trecolori-new-york',
        name: 'Trattoria Trecolori',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/nL_iTlbmA__6yNAAj1Xldg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/trattoria-trecolori-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 2428,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.759876,
          longitude: -73.986767,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '254 West 47th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['254 West 47th St', 'New York, NY 10036'],
        },
        phone: '+12129974540',
        display_phone: '(212) 997-4540',
        distance: 896.6502084561056,
      },
      {
        id: '-QVywSt3181U8ZGkUF-h7Q',
        alias: 'z-deli-pizzeria-new-york',
        name: 'Z Deli Pizzeria',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/idLmjQYFX94AN3BZkGXmvw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/z-deli-pizzeria-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 75,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7613895833492,
          longitude: -73.9868286252022,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '803 8th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['803 8th Ave', 'New York, NY 10019'],
        },
        phone: '+12123151659',
        display_phone: '(212) 315-1659',
        distance: 764.0798956347483,
      },
      {
        id: 'fBmdOCTJuh0bYMFoLvgEaw',
        alias: 'justinos-pizzeria-new-york',
        name: "Justino's Pizzeria",
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/uHmrhgF6e_6dqglruXL4bw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/justinos-pizzeria-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 262,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.76945,
          longitude: -73.98854,
        },
        transactions: ['delivery', 'pickup'],
        price: '$',
        location: {
          address1: '881 10th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['881 10th Ave', 'New York, NY 10019'],
        },
        phone: '+12125821222',
        display_phone: '(212) 582-1222',
        distance: 614.7561890463354,
      },
      {
        id: 'MOwB9YYd-Ko6nVgSB-ltQw',
        alias: 'briciola-new-york',
        name: 'Briciola',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/eO9jNBCXTg5yxxnbpLrkeA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/briciola-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 892,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'wine_bars',
            title: 'Wine Bars',
          },
          {
            alias: 'tapas',
            title: 'Tapas Bars',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7637997047278,
          longitude: -73.9880919456482,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '370 W 51st St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['370 W 51st St', 'New York, NY 10019'],
        },
        phone: '+16466785763',
        display_phone: '(646) 678-5763',
        distance: 542.9956599911184,
      },
      {
        id: 'QR7eMOsOXxGg26xx4wQUOw',
        alias: 'bar-dough-new-york',
        name: 'Bar Dough',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/ebOurPIMdHPiwbSghrBBgg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/bar-dough-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 111,
        categories: [
          {
            alias: 'bars',
            title: 'Bars',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'newamerican',
            title: 'American (New)',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 40.7603523698496,
          longitude: -73.9898819848895,
        },
        transactions: ['restaurant_reservation', 'delivery', 'pickup'],
        location: {
          address1: '350 W 46th St',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['350 W 46th St', 'New York, NY 10036'],
        },
        phone: '+19172620543',
        display_phone: '(917) 262-0543',
        distance: 699.5720408160486,
      },
      {
        id: 'RX7GKeE_9BPaKkxFqcUnFQ',
        alias: 'mamas-pizza-new-york-2',
        name: "Mama's Pizza",
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/76YpC_SOOSkrXDeB58NFnw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/mamas-pizza-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 45,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 2.5,
        coordinates: {
          latitude: 40.758897,
          longitude: -73.9887534,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '705 8th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['705 8th Ave', 'New York, NY 10036'],
        },
        phone: '+12129563400',
        display_phone: '(212) 956-3400',
        distance: 878.1398079169371,
      },
      {
        id: 'YLm2NzBuIZZqncRakdBZHg',
        alias: '42nd-street-restaurant-and-pizza-new-york',
        name: '42nd Street Restaurant and Pizza',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/vSB3H-xjde_Cw4_shQchKg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/42nd-street-restaurant-and-pizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 93,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'greek',
            title: 'Greek',
          },
          {
            alias: 'sandwiches',
            title: 'Sandwiches',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.7619413,
          longitude: -74.0001028,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '647 W 42nd St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['647 W 42nd St', 'New York, NY 10036'],
        },
        phone: '+12125944312',
        display_phone: '(212) 594-4312',
        distance: 675.3022062514286,
      },
      {
        id: 'HpxYBu1ARzOGvuUcLJe54g',
        alias: 'giardino-54-new-york',
        name: 'Giardino 54',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/zTMKugBklPSSQWlvInT3_Q/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/giardino-54-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 144,
        categories: [
          {
            alias: 'wine_bars',
            title: 'Wine Bars',
          },
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'cocktailbars',
            title: 'Cocktail Bars',
          },
        ],
        rating: 4.5,
        coordinates: {
          latitude: 40.7661,
          longitude: -73.98763,
        },
        transactions: ['restaurant_reservation', 'delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '402 W 54th St',
          address2: '400 1/2 W 54th St',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: [
            '402 W 54th St',
            '400 1/2 W 54th St',
            'New York, NY 10019',
          ],
        },
        phone: '+16467264575',
        display_phone: '(646) 726-4575',
        distance: 535.1519807518773,
      },
      {
        id: '0axnkZlDiQcJVc06DDXxGQ',
        alias: 'ristorante-il-melograno-new-york',
        name: 'Ristorante Il Melograno',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/92yZ46wiYeh2y4ng4NVBHA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/ristorante-il-melograno-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 341,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'desserts',
            title: 'Desserts',
          },
          {
            alias: 'salad',
            title: 'Salad',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7654289685161,
          longitude: -73.9914178848267,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '501 W 51st St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['501 W 51st St', 'New York, NY 10019'],
        },
        phone: '+12127579290',
        display_phone: '(212) 757-9290',
        distance: 218.1450995042606,
      },
      {
        id: 'u-MUL83NUy2gsbV80WZnAA',
        alias: 'the-marshal-new-york',
        name: 'The Marshal',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/YF9TFTrmQV1_e7YnPiNmFg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/the-marshal-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 767,
        categories: [
          {
            alias: 'breakfast_brunch',
            title: 'Breakfast & Brunch',
          },
          {
            alias: 'tradamerican',
            title: 'American (Traditional)',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.76122,
          longitude: -73.99396,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$$',
        location: {
          address1: '628 10th Ave',
          address2: null,
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['628 10th Ave', 'New York, NY 10036'],
        },
        phone: '+12125826300',
        display_phone: '(212) 582-6300',
        distance: 513.8312016634953,
      },
      {
        id: 'VgIiCZoUnujSMZATByk77Q',
        alias: 'the-meatball-shop-hells-kitchen-new-york',
        name: "The Meatball Shop - Hell's Kitchen",
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/hD59qPZaeYfgfiKndEaamg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/the-meatball-shop-hells-kitchen-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 424,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'tradamerican',
            title: 'American (Traditional)',
          },
          {
            alias: 'salad',
            title: 'Salad',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7651804928198,
          longitude: -73.9874866666706,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '798 9th Ave',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['798 9th Ave', 'New York, NY 10019'],
        },
        phone: '+12122305860',
        display_phone: '(212) 230-5860',
        distance: 549.3251311262933,
      },
      {
        id: 'iWshqIt2SBMVeLAKwKbm8A',
        alias: 'mama-pizza-and-more-new-york-2',
        name: 'Mama Pizza and More',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/dfagUEfx3wexZpg2u69ziQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/mama-pizza-and-more-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 1,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 5,
        coordinates: {
          latitude: 40.763643,
          longitude: -73.988463,
        },
        transactions: ['delivery'],
        location: {
          address1: '748 9th Ave',
          address2: null,
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['748 9th Ave', 'New York, NY 10019'],
        },
        phone: '+19173883144',
        display_phone: '(917) 388-3144',
        distance: 521.877151857399,
      },
      {
        id: '4K0doiBddco60kl0W04a3Q',
        alias: 'il-forno-hells-kitchen-new-york-2',
        name: "Il Forno Hell's Kitchen",
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/qpeA4jZePn36fb1TFJq-Sg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/il-forno-hells-kitchen-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 264,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7591217147251,
          longitude: -73.988647715231,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '709  8th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['709  8th Ave', 'New York, NY 10036'],
        },
        phone: '+19179949663',
        display_phone: '(917) 994-9663',
        distance: 870.1162962240953,
      },
      {
        id: 'bBDzXNM7Y7_8WE2Sm6R_ig',
        alias: 'gotham-west-market-new-york',
        name: 'Gotham West Market',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/S7r3KwRNhxK5otFw1FN_zQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/gotham-west-market-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 560,
        categories: [
          {
            alias: 'food_court',
            title: 'Food Court',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7624395,
          longitude: -73.9971462,
        },
        transactions: [],
        price: '$$',
        location: {
          address1: '600 11th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['600 11th Ave', 'New York, NY 10036'],
        },
        phone: '+12125827940',
        display_phone: '(212) 582-7940',
        distance: 463.80162657195285,
      },
      {
        id: 'BzIU7EHdj8OSuPkaG9L53Q',
        alias: 'i-heart-pizza-new-york-2',
        name: 'I Heart Pizza',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/9sGTN30cQJ5A8RUUvY7cJg/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/i-heart-pizza-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 7,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 2,
        coordinates: {
          latitude: 40.76265,
          longitude: -73.98996,
        },
        transactions: ['delivery', 'pickup'],
        location: {
          address1: '707 9th Ave',
          address2: null,
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['707 9th Ave', 'New York, NY 10019'],
        },
        phone: '+19174600315',
        display_phone: '(917) 460-0315',
        distance: 484.1686370308251,
      },
      {
        id: 'u5gLdI6l6zsPxL2kOYbyfw',
        alias: 'nizza-new-york',
        name: 'Nizza',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/7ZQrVoCZeqfjdNuqE3JfOw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/nizza-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 796,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'bars',
            title: 'Bars',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.76018,
          longitude: -73.99113,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '630 9th Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['630 9th Ave', 'New York, NY 10036'],
        },
        phone: '+12129561800',
        display_phone: '(212) 956-1800',
        distance: 689.5839898615452,
      },
      {
        id: 'jut4gYpjy2lT13h6sESfSQ',
        alias: 'olympic-flame-diner-new-york',
        name: 'Olympic Flame Diner',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/0rEkIKUoEWifjkzk-IJ8ZA/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/olympic-flame-diner-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 216,
        categories: [
          {
            alias: 'diners',
            title: 'Diners',
          },
          {
            alias: 'tradamerican',
            title: 'American (Traditional)',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
        ],
        rating: 3,
        coordinates: {
          latitude: 40.7709421554512,
          longitude: -73.9873045515683,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '200 W 60th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10023',
          country: 'US',
          state: 'NY',
          display_address: ['200 W 60th St', 'New York, NY 10023'],
        },
        phone: '+12125815259',
        display_phone: '(212) 581-5259',
        distance: 797.2349501860699,
      },
      {
        id: 'GZvelhGenbfJxc4_SG_RJw',
        alias: 'cielo-italian-restaurant-new-york-2',
        name: 'Cielo Italian Restaurant',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/fsmwVFzwwQ5y_hBvpWctMQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/cielo-italian-restaurant-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 448,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'cocktailbars',
            title: 'Cocktail Bars',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.76128,
          longitude: -73.9859,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '242 W 49th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['242 W 49th St', 'New York, NY 10019'],
        },
        phone: '+12124898600',
        display_phone: '(212) 489-8600',
        distance: 849.2897317965255,
      },
      {
        id: '8-Ug0Zjs5sL6MARspRJ7CA',
        alias: 'bond-45-new-york-2',
        name: 'Bond 45',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/CEfwtx0YtfDGog0hWmQ72A/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/bond-45-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 739,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'newamerican',
            title: 'American (New)',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.7591637016814,
          longitude: -73.9859788257256,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '221 W 46th St',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['221 W 46th St', 'New York, NY 10036'],
        },
        phone: '+12128694545',
        display_phone: '(212) 869-4545',
        distance: 1000.7446199901908,
      },
      {
        id: 'AfiSqDmx7Q3qLLgAvhHSRQ',
        alias: 'blue-seafood-bar-new-york',
        name: 'Blue Seafood Bar',
        image_url:
          'https://s3-media1.fl.yelpcdn.com/bphoto/ph6rwlLJ6pyYEq2Ol67b7w/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/blue-seafood-bar-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 173,
        categories: [
          {
            alias: 'seafood',
            title: 'Seafood',
          },
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'mediterranean',
            title: 'Mediterranean',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.76685,
          longitude: -73.98615,
        },
        transactions: ['restaurant_reservation', 'delivery', 'pickup'],
        price: '$$$',
        location: {
          address1: '856 Ninth Ave',
          address2: '',
          address3: '',
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['856 Ninth Ave', 'New York, NY 10019'],
        },
        phone: '+12127577511',
        display_phone: '(212) 757-7511',
        distance: 663.4665682042488,
      },
      {
        id: 'fmdEiai0e4agyTEqFUWJmw',
        alias: 'amarone-ny-new-york-2',
        name: 'Amarone NY',
        image_url:
          'https://s3-media2.fl.yelpcdn.com/bphoto/0zdaK9UpCwLEpX7VKPx_nw/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/amarone-ny-new-york-2?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 332,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'seafood',
            title: 'Seafood',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.7617199,
          longitude: -73.99002,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '686 9th Ave',
          address2: 'Ste 1',
          address3: '',
          city: 'New York',
          zip_code: '10036',
          country: 'US',
          state: 'NY',
          display_address: ['686 9th Ave', 'Ste 1', 'New York, NY 10036'],
        },
        phone: '+12122456060',
        display_phone: '(212) 245-6060',
        distance: 569.8259626572176,
      },
      {
        id: 'A5MHd0GjEb4P86UsNzUnig',
        alias: 'sesamo-new-york',
        name: 'SESAMO',
        image_url:
          'https://s3-media3.fl.yelpcdn.com/bphoto/Y9fS6W7C7mQCMw4OPcMPhQ/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/sesamo-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 212,
        categories: [
          {
            alias: 'italian',
            title: 'Italian',
          },
          {
            alias: 'wine_bars',
            title: 'Wine Bars',
          },
          {
            alias: 'cocktailbars',
            title: 'Cocktail Bars',
          },
        ],
        rating: 4,
        coordinates: {
          latitude: 40.765726,
          longitude: -73.990678,
        },
        transactions: ['delivery', 'pickup'],
        price: '$$',
        location: {
          address1: '764 10th Ave',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['764 10th Ave', 'New York, NY 10019'],
        },
        phone: '+12122652755',
        display_phone: '(212) 265-2755',
        distance: 274.0436802102271,
      },
      {
        id: '_J2wfGgCtx4wT05VK3S75w',
        alias: 'amore-pizza-cafe-new-york',
        name: 'Amore Pizza Cafe',
        image_url:
          'https://s3-media4.fl.yelpcdn.com/bphoto/yW4HiEqCumDgwfgRX7vS5A/o.jpg',
        is_closed: false,
        url: 'https://www.yelp.com/biz/amore-pizza-cafe-new-york?adjust_creative=iGT8XeHTfr6cW1JZxqC-TA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=iGT8XeHTfr6cW1JZxqC-TA',
        review_count: 10,
        categories: [
          {
            alias: 'pizza',
            title: 'Pizza',
          },
          {
            alias: 'cafes',
            title: 'Cafes',
          },
        ],
        rating: 3.5,
        coordinates: {
          latitude: 40.76833171568801,
          longitude: -73.98512273713298,
        },
        transactions: ['delivery', 'pickup'],
        location: {
          address1: '370 W 58th St',
          address2: '',
          address3: null,
          city: 'New York',
          zip_code: '10019',
          country: 'US',
          state: 'NY',
          display_address: ['370 W 58th St', 'New York, NY 10019'],
        },
        phone: '+12125814200',
        display_phone: '(212) 581-4200',
        distance: 793.5819678568957,
      },
    ],
    total: 112,
    region: {
      center: {
        longitude: -73.9939515,
        latitude: 40.765837,
      },
    },
  };
  return data;
};

export default dataFunction;
